### ISSUE TITLE
Create footer and update css for feature page

### ISSUE THREAD

**Issue by zerubabel4** [lab-brussels-1/loruki-group-1#25]
## Docs
 - [x] correct CSS
 - [x] footer

**Comment by bermarte** [comment]
It's not entirely clear to me what this ticket is about. By reading the issue one should be able to understand all the steps involved.

An example of user story that you could have in an issue would be like:

```
Acception Criteria

GIVEN that I am looking at the homepage
WHEN I click on the header
THEN I can see the detail page of the firm on the website.

GIVEN that I need to see the phone number of the business
WHEN I click on a the contact button
THEN a new contact page is shown on the website. 
```

**Comment by minjupgeorge** [comment]
Ok Understood. @bermarte ..we will correct it.
Thank you
