### ISSUE TITLE
Create A Agile Development

### ISSUE THREAD

**Issue by zerubabel4** [lab-brussels-1/loruki-group-1#37]
- [x] [repo](https://github.com/_/_) (with a complete README)
- [ ] [live demo](https://_.github.io/_) (GitHub Pages, not Netlify)
- [/planning](https://github.com/_/_/tree/master/planning)
  - [ ] constraints
  - [ ] communication plan
  - [ ] user personas
  - [ ] backlog
  - [ ] design
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board](https://github.com/_/_/projects/1)

**Comment by minjupgeorge** [comment]
This is deliverable issue that i have already put in here:
https://github.com/lab-brussels-1/home/issues
